apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config-map
  labels:
    name: grafana
    app: logging-app
data:
    default.yml: |- # This is the Item key
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false