apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    name: loki
    app: logging-app
spec:
  selector:
    app: logging-app #should be match with deployments metadata.labels.app: logging-app
    name: loki #should be match with deployments metadata.labels.name: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP
